package settings.dto;

public interface DeviceConfigurationSettingsConstants {
	
	public String AFFORDABLE_ON_TIME_DELAY = "AFFORDABLE ON TIME DELAY";
	public String PRE_START_DELAY_FOR_IN = "PRE START DELAY FOR IN";
	public String POST_START_DELAY_FOR_IN = "POST START DELAY FOR IN";
	public String PRE_STOP_DELAY_FOR_OUT = "PRE STOP DELAY FOR OUT";
	public String POST_STOP_DELAY_FOR_OUT = "POST STOP DELAY FOR OUT";
	public String TRIP_START_VALIDATION = "TRIP START VALIDATION";
	public String TRIP_STOP_VALIDATION = "TRIP STOP VALIDATION";
	public String PRE_STOP_DELAY_FOR_IN = "PRE STOP DELAY FOR IN";
	public String POST_STOP_DELAY_FOR_IN = "POST STOP DELAY FOR IN";
	public String PRE_START_DELAY_FOR_OUT = "PRE START DELAY FOR OUT";
	public String POST_START_DELAY_FOR_OUT = "POST START DELAY FOR OUT";
	public String DOUBLE_AUTHENTICATION_FOR_EMPLOYEE_PICKUP = "DOUBLE AUTHENTICATION FOR EMPLOYEE PICKUP";
	public String DOUBLE_AUTHENTICATION_FOR_EMPLOYEE_DROP = "DOUBLE AUTHENTICATION FOR EMPLOYEE DROP";
	public String DOUBLE_AUTHENTICATION_FOR_ESCORT_PICKUP = "DOUBLE AUTHENTICATION FOR ESCORT PICKUP";
	public String DOUBLE_AUTHENTICATION_FOR_ESCORT_DROP = "DOUBLE AUTHENTICATION FOR ESCORT DROP";
	public String FIRST_ESCORT_AUTH_BEFORE_EMP_AUTH_PICKUP = "FIRST ESCORT  AUTH BEFORE EMP AUTH PICKUP";
	public String SECOND_ESCORT_AUTH_AFTER_EMP_AUTH_PICKUP = "SECOND ESCORT AUTH AFTER EMP AUTH PICKUP";
	public String FIRST_ESCORT_AUTH_BEFORE_EMP_AUTH_DROP = "FIRST ESCORTAUTHENTICATION BEFORE EMPLOYEE AUTHENTICATION DROP";
	public String SECOND_ESCORT_AUTH_AFTER_EMP_AUTH_DROP = "SECOND ESCORTAUTHENTICATION AFTER EMPLOYEE AUTHENTICATION DROP";
	public String AUTOMATIC_DEVICE_VEHICLE_MAPPING =  "AUTOMATIC DEVICE VEHICLE MAPPING";


}
